Altera pipeline terraform apply

diff --git a/.github/workflows/apply-pipeline.yml b/.github/workflows/apply-pipeline.yml
--- a/.github/workflows/apply-pipeline.yml
+++ b/.github/workflows/apply-pipeline.yml
@@ -4,17 +4,113 @@ on:
   push:
     branches:
       - main
+  pull_request:
+    branches:
+      - main
+
+permissions:
+  id-token: write
+  contents: read
+  pull-requests: write
       
+env:
+  TF_VAR_mysql_user: ${{ secrets.TF_VAR_MYSQL_USER }}
+  TF_VAR_mysql_password: ${{ secrets.TF_VAR_MYSQL_PASSWORD }}
+  TF_VAR_mysql_server_name: ${{ secrets.TF_VAR_MYSQL_SERVER_NAME }}
+  TF_VAR_private_dns_zone_name: ${{ secrets.TF_VAR_PRIVATE_DNS_ZONE_NAME }}
+  ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
+  ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
+  ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
+  ARM_TENANT_ID: ${{ secrets.TF_ARM_TENANT_ID }}
+  
+
 jobs:
-  Apply:
+  terraform-plan:
+    name: 'Terraform Plan'
     runs-on: ubuntu-latest
 
-    env:
-      TF_VAR_mysql_user: ${{ secrets.TF_VAR_MYSQL_USER }}
-      TF_VAR_mysql_password: ${{ secrets.TF_VAR_MYSQL_PASSWORD }}
-      TF_VAR_mysql_server_name: ${{ secrets.TF_VAR_MYSQL_SERVER_NAME }}
-      TF_VAR_private_dns_zone_name: ${{ secrets.TF_VAR_PRIVATE_DNS_ZONE_NAME }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4.1.1
 
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2.0.3
+        with:
+          terraform_version: 1.7.2
+      
+      - name: Terraform Init
+        run: terraform init
+
+      - name: Terraform Format
+        run: terraform fmt -check
+    
+      # Exit codes: 0 = sem mudanças, 1 = falha, 2 = existem mudanças pendentes
+      - name: Terraform Plan
+        id: tf-plan
+        run: |
+          export exitcode=0
+          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+  
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+          
+          if [ $exitcode -eq 1 ]; then
+            echo Terraform Plan Failed!
+            exit 1
+          else 
+            exit 0
+          fi
+          
+      - name: Publish Terraform Plan
+        uses: actions/upload-artifact@v4.3.1
+        with:
+          name: tfplan
+          path: tfplan
+          
+      - name: Create String Output
+        id: tf-plan-string
+        run: |
+          TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+          
+          delimiter="$(openssl rand -hex 8)"
+          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+          echo "" >> $GITHUB_OUTPUT
+          echo '```terraform' >> $GITHUB_OUTPUT
+          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+          echo '```' >> $GITHUB_OUTPUT
+          echo "</details>" >> $GITHUB_OUTPUT
+          echo "${delimiter}" >> $GITHUB_OUTPUT
+          
+      - name: Publish Terraform Plan to Task Summary
+        env:
+          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+        run: |
+          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+        
+      - name: Push Terraform Output to PR
+        if: github.ref != 'refs/heads/main'
+        uses: actions/github-script@v6
+        env:
+          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
+        with:
+            github-token: ${{ secrets.GITHUB_TOKEN }}
+            script: |
+              const body = `${process.env.SUMMARY}`;
+              github.rest.issues.createComment({
+                  issue_number: context.issue.number,
+                  owner: context.repo.owner,
+                  repo: context.repo.repo,
+                  body: body
+              })
+  
+
+  terraform-apply:
+    name: 'Terraform Apply'
+    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
+    runs-on: ubuntu-latest
+    needs: [terraform-plan]
+    
     steps:
       - name: Checkout code
         uses: actions/checkout@v4.1.1
@@ -25,22 +121,15 @@ jobs:
           terraform_version: 1.7.2
 
       - name: Terraform Init
-        id: init
-        env:
-          ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
-          ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
-          ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
-          ARM_TENANT_ID: ${{ secrets.TF_ARM_TENANT_ID }}
-          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
-          STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
-          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
-        run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"
-                  
+        run: terraform init
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan -no-color
-      
+      - name: Download Terraform Plan
+        uses: actions/download-artifact@v3
+        with:
+          name: tfplan
+
       - name: Terraform Apply
-        id: apply
-        run: terraform apply -auto-approve
+        run: terraform apply -auto-approve tfplan
+
+
+                    
